// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Atom = require("atom");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function toPoint(param) {
  return new Atom.Point(param[1] - 1 | 0, param[2] - 1 | 0);
}

function fromPoint(filepath, point) {
  return /* Pos */Caml_chrome_debugger.simpleVariant("Pos", [
            filepath,
            point.row + 1 | 0,
            point.column + 1 | 0
          ]);
}

var Pos = {
  toPoint: toPoint,
  fromPoint: fromPoint
};

function toRange(param) {
  if (param) {
    var match = param[1];
    return new Atom.Range(toPoint(param[0]), new Atom.Point(match[1] - 1 | 0, match[2]));
  } else {
    return new Atom.Range(new Atom.Point(0, 0), new Atom.Point(0, 0));
  }
}

function fromRange(filepath, range) {
  var start = range.start;
  var end_ = range.end;
  return /* Loc */Caml_chrome_debugger.simpleVariant("Loc", [
            /* Pos */Caml_chrome_debugger.simpleVariant("Pos", [
                filepath,
                start.row + 1 | 0,
                start.column + 1 | 0
              ]),
            /* Pos */Caml_chrome_debugger.simpleVariant("Pos", [
                filepath,
                end_.row + 1 | 0,
                end_.column
              ])
          ]);
}

var Loc = {
  toRange: toRange,
  fromRange: fromRange
};

exports.Pos = Pos;
exports.Loc = Loc;
/* atom Not a pure module */
