// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var $$Request = 0;

var $$Error = 0;

var $$Response = 0;

exports.$$Request = $$Request;
exports.$$Error = $$Error;
exports.$$Response = $$Response;
/* No side effect */
