// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Base$GclAtom = require("./Base.bs.js");
var Util$GclAtom = require("../Util/Util.bs.js");
var Syntax$GclAtom = require("./Syntax.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var decode = Util$GclAtom.Decode.sum((function (tag) {
        switch (tag) {
          case "AtAbort" :
              var partial_arg = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtAbort */Caml_chrome_debugger.variant("AtAbort", 0, [x]);
                                        }), partial_arg, param);
                          })]);
          case "AtAssertion" :
              var partial_arg$1 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtAssertion */Caml_chrome_debugger.variant("AtAssertion", 4, [x]);
                                        }), partial_arg$1, param);
                          })]);
          case "AtAssignment" :
              var partial_arg$2 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtAssignment */Caml_chrome_debugger.variant("AtAssignment", 3, [x]);
                                        }), partial_arg$2, param);
                          })]);
          case "AtBoundDecrement" :
              var partial_arg$3 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtBoundDecrement */Caml_chrome_debugger.variant("AtBoundDecrement", 9, [x]);
                                        }), partial_arg$3, param);
                          })]);
          case "AtIf" :
              var partial_arg$4 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtIf */Caml_chrome_debugger.variant("AtIf", 6, [x]);
                                        }), partial_arg$4, param);
                          })]);
          case "AtLoop" :
              var partial_arg$5 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtLoop */Caml_chrome_debugger.variant("AtLoop", 7, [x]);
                                        }), partial_arg$5, param);
                          })]);
          case "AtLoopInvariant" :
              var partial_arg$6 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtLoopInvariant */Caml_chrome_debugger.variant("AtLoopInvariant", 5, [x]);
                                        }), partial_arg$6, param);
                          })]);
          case "AtSkip" :
              var partial_arg$7 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtSkip */Caml_chrome_debugger.variant("AtSkip", 1, [x]);
                                        }), partial_arg$7, param);
                          })]);
          case "AtSpec" :
              var partial_arg$8 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtSpec */Caml_chrome_debugger.variant("AtSpec", 2, [x]);
                                        }), partial_arg$8, param);
                          })]);
          case "AtTermination" :
              var partial_arg$9 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AtTermination */Caml_chrome_debugger.variant("AtTermination", 8, [x]);
                                        }), partial_arg$9, param);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

function toString(param) {
  switch (param.tag | 0) {
    case /* AtAbort */0 :
        return "Abort";
    case /* AtSkip */1 :
        return "Skip";
    case /* AtSpec */2 :
        return "Spec";
    case /* AtAssignment */3 :
        return "Assignment";
    case /* AtAssertion */4 :
        return "Assertion";
    case /* AtLoopInvariant */5 :
        return "Loop Invariant";
    case /* AtIf */6 :
        return "Conditional";
    case /* AtLoop */7 :
        return "Loop";
    case /* AtTermination */8 :
        return "Termination";
    case /* AtBoundDecrement */9 :
        return "Bound Decrement";
    
  }
}

function locOf(param) {
  return param[0];
}

var Origin = {
  decode: decode,
  toString: toString,
  locOf: locOf
};

var partial_arg = Syntax$GclAtom.Pred.decode;

var partial_arg$1 = Syntax$GclAtom.Pred.decode;

function partial_arg$2(param) {
  return Json_decode.tuple4(Json_decode.$$int, partial_arg$1, partial_arg, decode, param);
}

function decode$1(param) {
  return Json_decode.map((function (param) {
                return /* ProofObligation */Caml_chrome_debugger.simpleVariant("ProofObligation", [
                          param[0],
                          param[1],
                          param[2],
                          param[3]
                        ]);
              }), partial_arg$2, param);
}

var ProofObligation = {
  decode: decode$1
};

function decode$2(json) {
  return /* record */Caml_chrome_debugger.record([
            "id",
            "pre",
            "post",
            "loc"
          ], [
            Json_decode.field("specID", Json_decode.$$int, json),
            Json_decode.field("specPreCond", Syntax$GclAtom.Pred.decode, json),
            Json_decode.field("specPostCond", Syntax$GclAtom.Pred.decode, json),
            Json_decode.field("specLoc", Base$GclAtom.Loc.decode, json)
          ]);
}

var Specification = {
  decode: decode$2
};

function toLoc(site, specifications) {
  if (site.tag) {
    var i = site[1];
    var loc = site[0];
    var specs = Rebase.$$Array.filter((function (spec) {
            return spec[/* id */0] === i;
          }), specifications);
    return Rebase.$$Option.mapOr((function (spec) {
                  return Base$GclAtom.Loc.translateBy(1, 0, 1, 0, Base$GclAtom.Loc.translate(loc, spec[/* loc */3]));
                }), loc, Rebase.$$Array.get(specs, 0));
  } else {
    return site[0];
  }
}

function toRange(site, specifications) {
  return Base$GclAtom.Loc.toRange(toLoc(site, specifications));
}

function toString$1(site) {
  if (site.tag) {
    return "at " + (Base$GclAtom.Loc.toString(site[0]) + (" in #" + String(site[1])));
  } else {
    return "at " + Base$GclAtom.Loc.toString(site[0]);
  }
}

var decode$3 = Util$GclAtom.Decode.sum((function (tag) {
        switch (tag) {
          case "Global" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* Global */Caml_chrome_debugger.variant("Global", 0, [Curry._1(Base$GclAtom.Loc.decode, json)]);
                          })]);
          case "Local" :
              var partial_arg = Base$GclAtom.Loc.decode;
              var partial_arg$1 = function (param) {
                return Json_decode.pair(partial_arg, Json_decode.$$int, param);
              };
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* Local */Caml_chrome_debugger.variant("Local", 1, [
                                                    param[0],
                                                    param[1]
                                                  ]);
                                        }), partial_arg$1, param);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

var Site = {
  toLoc: toLoc,
  toRange: toRange,
  toString: toString$1,
  decode: decode$3
};

var decode$4 = Util$GclAtom.Decode.sum((function (tag) {
        switch (tag) {
          case "NotFunction" :
              var partial_arg = Base$GclAtom.Loc.decode;
              var partial_arg$1 = Syntax$GclAtom.Type.decode;
              var partial_arg$2 = function (param) {
                return Json_decode.pair(partial_arg$1, partial_arg, param);
              };
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* NotFunction */Caml_chrome_debugger.variant("NotFunction", 3, [param[0]]);
                                        }), partial_arg$2, param);
                          })]);
          case "NotInScope" :
              var partial_arg$3 = Base$GclAtom.Loc.decode;
              var partial_arg$4 = function (param) {
                return Json_decode.pair(Json_decode.string, partial_arg$3, param);
              };
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* NotInScope */Caml_chrome_debugger.variant("NotInScope", 0, [param[0]]);
                                        }), partial_arg$4, param);
                          })]);
          case "RecursiveType" :
              var partial_arg$5 = Base$GclAtom.Loc.decode;
              var partial_arg$6 = Syntax$GclAtom.Type.decode;
              var partial_arg$7 = function (param) {
                return Json_decode.tuple3(Json_decode.$$int, partial_arg$6, partial_arg$5, param);
              };
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* RecursiveType */Caml_chrome_debugger.variant("RecursiveType", 2, [
                                                    param[0],
                                                    param[1]
                                                  ]);
                                        }), partial_arg$7, param);
                          })]);
          case "UnifyFailed" :
              var partial_arg$8 = Base$GclAtom.Loc.decode;
              var partial_arg$9 = Syntax$GclAtom.Type.decode;
              var partial_arg$10 = Syntax$GclAtom.Type.decode;
              var partial_arg$11 = function (param) {
                return Json_decode.tuple3(partial_arg$10, partial_arg$9, partial_arg$8, param);
              };
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* UnifyFailed */Caml_chrome_debugger.variant("UnifyFailed", 1, [
                                                    param[0],
                                                    param[1]
                                                  ]);
                                        }), partial_arg$11, param);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

var $$TypeError = {
  decode: decode$4
};

var decode$5 = Util$GclAtom.Decode.sum((function (tag) {
        switch (tag) {
          case "DigHole" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return /* DigHole */6;
                          })]);
          case "ExcessBound" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return /* ExcessBound */3;
                          })]);
          case "MissingAssertion" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return /* MissingAssertion */1;
                          })]);
          case "MissingBound" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return /* MissingBound */0;
                          })]);
          case "MissingLoopInvariant" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return /* MissingLoopInvariant */2;
                          })]);
          case "MissingPostcondition" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return /* MissingPostcondition */5;
                          })]);
          case "MissingPrecondition" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return /* MissingPrecondition */4;
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

var StructError = {
  decode: decode$5
};

var decodeKind = Util$GclAtom.Decode.sum((function (tag) {
        switch (tag) {
          case "CannotReadFile" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* CannotReadFile */Caml_chrome_debugger.variant("CannotReadFile", 3, [Json_decode.string(json)]);
                          })]);
          case "LexicalError" :
              return /* TagOnly */Caml_chrome_debugger.variant("TagOnly", 1, [(function (param) {
                            return /* LexicalError */0;
                          })]);
          case "NotLoaded" :
              return /* TagOnly */Caml_chrome_debugger.variant("TagOnly", 1, [(function (param) {
                            return /* NotLoaded */1;
                          })]);
          case "StructError2" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* StructError */Caml_chrome_debugger.variant("StructError", 1, [Curry._1(decode$5, json)]);
                          })]);
          case "SyntacticError" :
              var partial_arg = Base$GclAtom.Loc.decode;
              var partial_arg$1 = function (param) {
                return Json_decode.pair(partial_arg, Json_decode.string, param);
              };
              var partial_arg$2 = function (param) {
                return Json_decode.array(partial_arg$1, param);
              };
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (pairs) {
                                          return /* SyntacticError */Caml_chrome_debugger.variant("SyntacticError", 0, [Rebase.$$Array.map((function (prim) {
                                                            return prim[1];
                                                          }), pairs)]);
                                        }), partial_arg$2, param);
                          })]);
          case "TypeError" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* TypeError */Caml_chrome_debugger.variant("TypeError", 2, [Curry._1(decode$4, json)]);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

function decode$6(param) {
  return Json_decode.map((function (param) {
                return /* Error */Caml_chrome_debugger.simpleVariant("Error", [
                          param[0],
                          param[1]
                        ]);
              }), (function (param) {
                return Json_decode.pair(decode$3, decodeKind, param);
              }), param);
}

var $$Error = {
  Site: Site,
  $$TypeError: $$TypeError,
  StructError: StructError,
  decodeKind: decodeKind,
  decode: decode$6
};

var decode$7 = Util$GclAtom.Decode.sum((function (tag) {
        switch (tag) {
          case "Error" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (errors) {
                                          return /* Error */Caml_chrome_debugger.variant("Error", 0, [errors]);
                                        }), (function (param) {
                                          return Json_decode.array(decode$6, param);
                                        }), param);
                          })]);
          case "Insert" :
              var partial_arg = Syntax$GclAtom.Expr.decode;
              var partial_arg$1 = function (param) {
                return Json_decode.pair(Json_decode.$$int, partial_arg, param);
              };
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* InsertAssertion */Caml_chrome_debugger.variant("InsertAssertion", 3, [
                                                    param[0],
                                                    param[1]
                                                  ]);
                                        }), partial_arg$1, param);
                          })]);
          case "OK" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* OK */Caml_chrome_debugger.variant("OK", 1, [
                                                    param[0],
                                                    param[1]
                                                  ]);
                                        }), (function (param) {
                                          return Json_decode.pair((function (param) {
                                                        return Json_decode.array(decode$1, param);
                                                      }), (function (param) {
                                                        return Json_decode.array(decode$2, param);
                                                      }), param);
                                        }), param);
                          })]);
          case "Resolve" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (i) {
                                          return /* Resolve */Caml_chrome_debugger.variant("Resolve", 2, [i]);
                                        }), Json_decode.$$int, param);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

exports.Origin = Origin;
exports.ProofObligation = ProofObligation;
exports.Specification = Specification;
exports.$$Error = $$Error;
exports.decode = decode$7;
/* decode Not a pure module */
