// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Expr$GclAtom = require("../View/Expr.bs.js");
var Decoder$GclAtom = require("./Decoder.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function decode(json) {
  return /* record */Caml_chrome_debugger.record([
            "id",
            "pre",
            "post",
            "range"
          ], [
            Json_decode.field("specID", Json_decode.$$int, json),
            Json_decode.field("specPreCond", Expr$GclAtom.decode, json),
            Json_decode.field("specPostCond", Expr$GclAtom.decode, json),
            Json_decode.field("specLoc", Decoder$GclAtom.range, json)
          ]);
}

exports.decode = decode;
/* Expr-GclAtom Not a pure module */
