// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Base$GclAtom = require("../GCL/Base.bs.js");
var Pred$GclAtom = require("./Pred.bs.js");
var Util$GclAtom = require("../Util.bs.js");
var Syntax$GclAtom = require("../GCL/Syntax.bs.js");
var Decoder$GclAtom = require("../GCL/Decoder.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var decode = Decoder$GclAtom.sum((function (tag) {
        switch (tag) {
          case "AroundAbort" :
              var partial_arg = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AroundAbort */Caml_chrome_debugger.variant("AroundAbort", 0, [x]);
                                        }), partial_arg, param);
                          })]);
          case "AroundSkip" :
              var partial_arg$1 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AroundSkip */Caml_chrome_debugger.variant("AroundSkip", 1, [x]);
                                        }), partial_arg$1, param);
                          })]);
          case "AssertGuaranteed" :
              var partial_arg$2 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AssertGuaranteed */Caml_chrome_debugger.variant("AssertGuaranteed", 2, [x]);
                                        }), partial_arg$2, param);
                          })]);
          case "AssertSufficient" :
              var partial_arg$3 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* AssertSufficient */Caml_chrome_debugger.variant("AssertSufficient", 3, [x]);
                                        }), partial_arg$3, param);
                          })]);
          case "Assignment" :
              var partial_arg$4 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* Assignment */Caml_chrome_debugger.variant("Assignment", 4, [x]);
                                        }), partial_arg$4, param);
                          })]);
          case "IfBranch" :
              var partial_arg$5 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* IfBranch */Caml_chrome_debugger.variant("IfBranch", 6, [x]);
                                        }), partial_arg$5, param);
                          })]);
          case "IfTotal" :
              var partial_arg$6 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* IfTotal */Caml_chrome_debugger.variant("IfTotal", 5, [x]);
                                        }), partial_arg$6, param);
                          })]);
          case "LoopBase" :
              var partial_arg$7 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* LoopBase */Caml_chrome_debugger.variant("LoopBase", 7, [x]);
                                        }), partial_arg$7, param);
                          })]);
          case "LoopInd" :
              var partial_arg$8 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* LoopInd */Caml_chrome_debugger.variant("LoopInd", 8, [x]);
                                        }), partial_arg$8, param);
                          })]);
          case "LoopInitialize" :
              var partial_arg$9 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* LoopInitialize */Caml_chrome_debugger.variant("LoopInitialize", 11, [x]);
                                        }), partial_arg$9, param);
                          })]);
          case "LoopTermBase" :
              var partial_arg$10 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* LoopTermBase */Caml_chrome_debugger.variant("LoopTermBase", 9, [x]);
                                        }), partial_arg$10, param);
                          })]);
          case "LoopTermDec" :
              var partial_arg$11 = Base$GclAtom.Loc.decode;
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (x) {
                                          return /* LoopTermDec */Caml_chrome_debugger.variant("LoopTermDec", 10, [x]);
                                        }), partial_arg$11, param);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

function toString(param) {
  switch (param.tag | 0) {
    case /* AroundAbort */0 :
        return "AroundAbort";
    case /* AroundSkip */1 :
        return "AroundSkip";
    case /* AssertGuaranteed */2 :
        return "AssertGuaranteed";
    case /* AssertSufficient */3 :
        return "AssertSufficient";
    case /* Assignment */4 :
        return "Assignment";
    case /* IfTotal */5 :
        return "IfTotal";
    case /* IfBranch */6 :
        return "IfBranch";
    case /* LoopBase */7 :
        return "LoopBase";
    case /* LoopInd */8 :
        return "LoopInd";
    case /* LoopTermBase */9 :
        return "LoopTermBase";
    case /* LoopTermDec */10 :
        return "LoopTermDec";
    case /* LoopInitialize */11 :
        return "LoopInitialize";
    
  }
}

var Origin = {
  decode: decode,
  toString: toString
};

function Body$ProofObligation(Props) {
  var payload = Props.payload;
  var origins = Rebase.$$String.joinWith(" ", Rebase.List.fromArray(Rebase.$$Array.map(toString, payload[3])));
  return React.createElement("li", {
              className: "gcl-body-item native-key-bindings",
              tabIndex: -1
            }, React.createElement("span", {
                  className: "gcl-proof-obligation-message"
                }, origins), React.createElement("span", {
                  className: "gcl-proof-obligation-antecedent"
                }, React.createElement(Pred$GclAtom.make, {
                      value: payload[1]
                    })), React.createElement("span", {
                  className: "gcl-proof-obligation-arrow"
                }, "⇒"), React.createElement("span", {
                  className: "gcl-proof-obligation-consequent"
                }, React.createElement(Pred$GclAtom.make, {
                      value: payload[2]
                    })));
}

var partial_arg = Syntax$GclAtom.Pred.decode;

var partial_arg$1 = Syntax$GclAtom.Pred.decode;

function partial_arg$2(param) {
  return Json_decode.tuple4(Json_decode.$$int, partial_arg$1, partial_arg, (function (param) {
                return Json_decode.array(decode, param);
              }), param);
}

function decode$1(param) {
  return Json_decode.map((function (param) {
                return /* ProofObligation */Caml_chrome_debugger.simpleVariant("ProofObligation", [
                          param[0],
                          param[1],
                          param[2],
                          param[3]
                        ]);
              }), partial_arg$2, param);
}

var ProofObligation = {
  make: Body$ProofObligation,
  decode: decode$1
};

function Body(Props) {
  var body = Props.body;
  if (typeof body === "number") {
    return React.createElement(React.Fragment, undefined);
  } else if (body.tag) {
    var paragraphs = Util$GclAtom.React.manyIn("div", {
            className: "gcl-plain-text gcl-body-item"
          })(Rebase.$$Array.map((function (s) {
                return React.createElement("p", undefined, s);
              }), Rebase.$$Array.filter((function (x) {
                    return !Rebase.$$String.isEmpty(x);
                  }), body[0].split("\n"))));
    return React.createElement("div", {
                className: "gcl-body"
              }, paragraphs);
  } else {
    var ps = body[0];
    if (ps.length !== 0) {
      var list = Util$GclAtom.React.manyIn("ul", {
              className: "gcl-proof-obligation-list"
            })(Rebase.$$Array.map((function (payload) {
                  return React.createElement(Body$ProofObligation, {
                              payload: payload
                            });
                }), ps));
      return React.createElement("div", {
                  className: "gcl-body"
                }, list);
    } else {
      return React.createElement(React.Fragment, undefined);
    }
  }
}

var make = Body;

exports.Origin = Origin;
exports.ProofObligation = ProofObligation;
exports.make = make;
/* decode Not a pure module */
