// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Channel$GclAtom = require("../Util/Channel.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function make(param) {
  return /* record */Caml_chrome_debugger.record([
            "updateConnection",
            "setActivation",
            "setHeader",
            "setBody"
          ], [
            Channel$GclAtom.make(/* () */0),
            Channel$GclAtom.make(/* () */0),
            Channel$GclAtom.make(/* () */0),
            Channel$GclAtom.make(/* () */0)
          ]);
}

exports.make = make;
/* No side effect */
