// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Expr(Props) {
  return React.createElement("span", undefined, "hi");
}

var make = Expr;

exports.make = make;
/* react Not a pure module */
