// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Event$GclAtom = require("../Util/Event.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var emitter = Event$GclAtom.make(/* () */0);

var eventContext = React.createContext(emitter);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = eventContext.Provider;

var Provider = {
  makeProps: makeProps,
  make: make
};

function Link(Props) {
  var loc = Props.loc;
  var children = Props.children;
  var link = React.useContext(eventContext);
  var onMouseOver = function (param) {
    return Curry._1(link[/* emit */1], /* MouseOver */Caml_chrome_debugger.variant("MouseOver", 0, [loc]));
  };
  var onMouseLeave = function (param) {
    return Curry._1(link[/* emit */1], /* MouseLeave */Caml_chrome_debugger.variant("MouseLeave", 1, [loc]));
  };
  return React.createElement("div", {
              className: "expr-link",
              onMouseLeave: onMouseLeave,
              onMouseOver: onMouseOver
            }, children);
}

var make$1 = Link;

exports.emitter = emitter;
exports.eventContext = eventContext;
exports.Provider = Provider;
exports.make = make$1;
/* emitter Not a pure module */
