// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Hook$GclAtom = require("./Hook.bs.js");
var Async$GclAtom = require("../Util/Async.bs.js");

function Panel(Props) {
  var channels = Props.channels;
  var match = Hook$GclAtom.useState("");
  var setHeader = match[1];
  var match$1 = Hook$GclAtom.useState("");
  var setBody = match$1[1];
  var match$2 = Hook$GclAtom.useState(false);
  var setActivation = match$2[1];
  Hook$GclAtom.useChannel((function (x) {
          return Async$GclAtom.resolve(Curry._1(setHeader, x));
        }), channels[/* setHeader */2]);
  Hook$GclAtom.useChannel((function (x) {
          return Async$GclAtom.resolve(Curry._1(setBody, x));
        }), channels[/* setBody */3]);
  Hook$GclAtom.useChannel((function (x) {
          return Async$GclAtom.resolve(Curry._1(setActivation, x));
        }), channels[/* setActivation */1]);
  return React.createElement("section", {
              className: match$2[0] ? "" : "hidden"
            }, React.createElement("h2", undefined, match[0]), React.createElement("div", undefined, match$1[0]));
}

var make = Panel;

exports.make = make;
/* react Not a pure module */
