// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Caml_splice_call = require("bs-platform/lib/js/caml_splice_call.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function sum(decoder) {
  return (function (param) {
      return Json_decode.andThen((function (tag) {
                    var match = Curry._1(decoder, tag);
                    if (match.tag) {
                      return match[0];
                    } else {
                      var d = match[0];
                      return (function (param) {
                          return Json_decode.field("contents", d, param);
                        });
                    }
                  }), (function (param) {
                    return Json_decode.field("tag", Json_decode.string, param);
                  }), param);
    });
}

function maybe(decoder) {
  return sum((function (param) {
                if (param === "Just") {
                  return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                                return Caml_option.some(Curry._1(decoder, json));
                              })]);
                } else {
                  return /* TagOnly */Caml_chrome_debugger.variant("TagOnly", 1, [(function (param) {
                                return ;
                              })]);
                }
              }));
}

function tuple5(decodeA, decodeB, decodeC, decodeD, decodeE, json) {
  if (Array.isArray(json)) {
    var length = json.length;
    if (length === 5) {
      try {
        return /* tuple */[
                Curry._1(decodeA, json[0]),
                Curry._1(decodeB, json[1]),
                Curry._1(decodeC, json[2]),
                Curry._1(decodeD, json[3]),
                Curry._1(decodeE, json[4])
              ];
      }
      catch (raw_exn){
        var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
        if (exn[0] === Json_decode.DecodeError) {
          throw [
                Json_decode.DecodeError,
                exn[1] + "\n\tin tuple5"
              ];
        }
        throw exn;
      }
    } else {
      throw [
            Json_decode.DecodeError,
            "Expected array of length 5, got array of length " + (String(length) + "")
          ];
    }
  } else {
    throw [
          Json_decode.DecodeError,
          "Expected array, got " + JSON.stringify(json)
        ];
  }
}

var Decode = {
  sum: sum,
  maybe: maybe,
  tuple5: tuple5
};

function manyIn(elems, elem) {
  return Caml_splice_call.spliceApply(React.createElement, [
              elem,
              { },
              elems
            ]);
}

function manyIn2(elems, elem, props) {
  return Caml_splice_call.spliceApply(React.createElement, [
              elem,
              props,
              elems
            ]);
}

function sepBy$prime(item, sep) {
  if (item) {
    var xs = item[1];
    var x = item[0];
    if (xs) {
      return manyIn(Belt_List.toArray(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                        x,
                        Belt_List.map(xs, (function (i) {
                                return React.createElement(React.Fragment, undefined, sep, i);
                              }))
                      ])), "span");
    } else {
      return x;
    }
  } else {
    return React.createElement(React.Fragment, undefined);
  }
}

function sepBy(sep, xs) {
  return sepBy$prime(Belt_List.fromArray(xs), sep);
}

function enclosedBy(front, back, item) {
  return React.createElement(React.Fragment, undefined, front, " ", item, " ", back);
}

function when_(p, className) {
  if (p) {
    return " " + className;
  } else {
    return "";
  }
}

function showWhen(param) {
  if (param) {
    return "";
  } else {
    return " hidden";
  }
}

var React$1 = {
  manyIn: manyIn,
  manyIn2: manyIn2,
  sepBy$prime: sepBy$prime,
  sepBy: sepBy,
  enclosedBy: enclosedBy,
  when_: when_,
  showWhen: showWhen
};

function toString(_e) {
  return (_e.toString());
}

var JsError = {
  toString: toString
};

function every(xs) {
  return Belt_Array.reduce(xs, /* Ok */Caml_chrome_debugger.variant("Ok", 0, [[]]), (function (acc, x) {
                if (!acc.tag) {
                  var xs = acc[0];
                  if (!x.tag) {
                    xs.push(x[0]);
                    return /* Ok */Caml_chrome_debugger.variant("Ok", 0, [xs]);
                  }
                  
                }
                if (x.tag) {
                  return /* Error */Caml_chrome_debugger.variant("Error", 1, [x[0]]);
                } else {
                  return /* Error */Caml_chrome_debugger.variant("Error", 1, [acc[0]]);
                }
              }));
}

var Result = {
  every: every
};

exports.Decode = Decode;
exports.React = React$1;
exports.JsError = JsError;
exports.Result = Result;
/* react Not a pure module */
