// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Atom = require("atom");
var Curry = require("bs-platform/lib/js/curry.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function make(editor, param) {
  return {
          editor: editor,
          context: new Atom.CompositeDisposable()
        };
}

function getExtensionPath(param) {
  return Belt_Option.getWithDefault(atom.packages.resolvePackagePath("gcl-atom"), "");
}

function editorFileName(editor) {
  return Belt_Option.getWithDefault(editor.getPath(), "");
}

function addToSubscriptions(disposable, subscriptions) {
  subscriptions.add(disposable);
  return /* () */0;
}

function onDidCloseEditor(callback) {
  return atom.workspace.observeTextEditors((function (editor) {
                var subscriptions = new Atom.CompositeDisposable();
                subscriptions.add(editor.onDidDestroy((function (param) {
                            Belt_Option.forEach(editor.getPath(), callback);
                            subscriptions.dispose();
                            return /* () */0;
                          })));
                return /* () */0;
              }));
}

function onDidChangeFileName(callback) {
  return atom.workspace.observeTextEditors((function (editor) {
                var subscriptions = new Atom.CompositeDisposable();
                var previous = {
                  contents: editor.getPath()
                };
                subscriptions.add(editor.onDidChangePath((function (param) {
                            var next = editor.getPath();
                            if (Caml_obj.caml_notequal(next, previous.contents)) {
                              Curry._2(callback, previous.contents, next);
                              previous.contents = next;
                              return /* () */0;
                            } else {
                              return 0;
                            }
                          })));
                return /* () */0;
              }));
}

function onDidChangeActivation(callback) {
  var previous = {
    contents: atom.workspace.getActiveTextEditor()
  };
  return atom.workspace.onDidChangeActiveTextEditor((function (next) {
                if (Caml_obj.caml_notequal(next, previous.contents)) {
                  Curry._2(callback, Belt_Option.flatMap(previous.contents, (function (prim) {
                              return prim.getPath();
                            })), Belt_Option.flatMap(next, (function (prim) {
                              return prim.getPath();
                            })));
                  previous.contents = next;
                  return /* () */0;
                } else {
                  return 0;
                }
              }));
}

function registerCommand(name, callback) {
  var eventTargetEditor = function ($$event) {
    var targetSubElement = $$event.target;
    var targetedEditors = Belt_Array.keep(atom.workspace.getTextEditors(), (function (x) {
            return atom.views.getView(x).contains(targetSubElement);
          }));
    return Belt_Array.get(targetedEditors, 0);
  };
  return atom.commands.add("atom-text-editor", "gcl-atom:" + name, (function ($$event) {
                return Belt_Option.forEach(eventTargetEditor($$event), callback);
              }));
}

function setGCLPath(value) {
  atom.config.set("gcl-atom.path", value);
  return $$Promise.resolved(/* () */0);
}

function getGCLPath(param) {
  return atom.config.get("gcl-atom.path");
}

var Impl = {
  make: make,
  getExtensionPath: getExtensionPath,
  editorFileName: editorFileName,
  onDidChangeFileName: onDidChangeFileName,
  onDidChangeActivation: onDidChangeActivation,
  onDidCloseEditor: onDidCloseEditor,
  addToSubscriptions: addToSubscriptions,
  registerCommand: registerCommand,
  getGCLPath: getGCLPath,
  setGCLPath: setGCLPath
};

exports.Impl = Impl;
exports.make = make;
exports.getExtensionPath = getExtensionPath;
exports.editorFileName = editorFileName;
exports.onDidChangeFileName = onDidChangeFileName;
exports.onDidChangeActivation = onDidChangeActivation;
exports.onDidCloseEditor = onDidCloseEditor;
exports.addToSubscriptions = addToSubscriptions;
exports.registerCommand = registerCommand;
exports.getGCLPath = getGCLPath;
exports.setGCLPath = setGCLPath;
/* atom Not a pure module */
