// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("reason-promise/lib/js/src/js/promise.js");

function setGCLPath(value) {
  atom.config.set("gcl-atom.path", value);
  return $$Promise.resolved(/* () */0);
}

function getGCLPath(param) {
  return atom.config.get("gcl-atom.path");
}

var Impl = {
  getGCLPath: getGCLPath,
  setGCLPath: setGCLPath
};

exports.Impl = Impl;
exports.getGCLPath = getGCLPath;
exports.setGCLPath = setGCLPath;
/* Promise Not a pure module */
