// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var commandNames = /* array */[
  "toggle",
  "save",
  "refine",
  "insert-assertion",
  "debug"
];

function parse(param) {
  switch (param) {
    case "debug" :
        return /* Debug */4;
    case "insert-assertion" :
        return /* InsertAssertion */3;
    case "refine" :
        return /* Refine */2;
    case "save" :
        return /* Save */1;
    case "toggle" :
        return /* Toggle */0;
    default:
      return /* Save */1;
  }
}

var Local = {
  commandNames: commandNames,
  parse: parse
};

exports.Local = Local;
/* No side effect */
