// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Atom = require("atom");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Js_list = require("bs-platform/lib/js/js_list.js");
var Syntax$GclAtom = require("../GCL/Syntax.bs.js");
var ErrorSite$GclAtom = require("./ErrorSite.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function mark(type_, class_, range, editor) {
  var marker = editor.markBufferRange(range);
  var option = {
    type: type_,
    class: class_
  };
  return editor.decorateMarker(marker, option);
}

function markLineSpecSoft(param, param$1) {
  return mark("highlight", "highlight-spec-soft", param, param$1);
}

function markLineSpecHard(param, param$1) {
  return mark("highlight", "highlight-spec-hard", param, param$1);
}

function overlay(text, class_, tail, translation, range, editor) {
  var element = document.createElement("div");
  element.innerHTML = text;
  element.classList.add(class_);
  var top = (translation[0] - 1 | 0) * 1.5;
  element.setAttribute("style", "left: " + (String(translation[1]) + ("ex; top: " + (top.toString() + "em"))));
  var marker = editor.markBufferRange(range);
  var option = {
    type: "overlay",
    item: element,
    position: tail ? "tail" : "head"
  };
  return /* :: */Caml_chrome_debugger.simpleVariant("::", [
            editor.decorateMarker(marker, option),
            /* [] */0
          ]);
}

function overlaySpec(text) {
  var partial_arg = /* tuple */[
    0,
    1
  ];
  return (function (param, param$1) {
      return overlay(text, "overlay-spec-text", false, partial_arg, param, param$1);
    });
}

function overlayError(range, editor) {
  var length = editor.getTextInBufferRange(range).length;
  var text = "&nbsp;".repeat(length);
  return overlay(text, "overlay-error", true, /* tuple */[
              0,
              0
            ], range, editor);
}

function markSpec(spec, editor) {
  var start = spec[/* range */3].start;
  var start$1 = new Atom.Range(start, start.translate(new Atom.Point(0, 2)));
  var end_ = spec[/* range */3].end;
  var end_$1 = new Atom.Range(end_.translate(new Atom.Point(0, -2)), end_);
  var trim = function (s) {
    if (Rebase.$$String.length(s) > 77) {
      return Rebase.$$String.sub(0, 73, s) + " ...";
    } else {
      return s;
    }
  };
  var pre = trim(Syntax$GclAtom.Expr.toString(spec[/* pre */1]));
  var post = trim(Syntax$GclAtom.Expr.toString(spec[/* post */2]));
  return Rebase.$$Array.fromList(Js_list.flatten(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                    overlaySpec(pre)(start$1, editor),
                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        overlaySpec(post)(end_$1, editor),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                markLineSpecSoft(end_$1, editor),
                                /* [] */0
                              ]),
                            /* [] */0
                          ])
                      ])
                  ])));
}

function markSite(site, specifications, editor) {
  var range = ErrorSite$GclAtom.toRange(site, specifications);
  return Rebase.$$Array.fromList(Js_list.flatten(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                    overlayError(range, editor),
                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            mark("line-number", "line-number-error", range, editor),
                            /* [] */0
                          ]),
                        /* [] */0
                      ])
                  ])));
}

function markLink(param, param$1) {
  return mark("highlight", "highlight-link", param, param$1);
}

exports.mark = mark;
exports.markLineSpecSoft = markLineSpecSoft;
exports.markLineSpecHard = markLineSpecHard;
exports.overlay = overlay;
exports.overlaySpec = overlaySpec;
exports.overlayError = overlayError;
exports.markSpec = markSpec;
exports.markSite = markSite;
exports.markLink = markLink;
/* atom Not a pure module */
