// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Base$GclAtom = require("../GCL/Base.bs.js");
var Decoder$GclAtom = require("../GCL/Decoder.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var decode = Decoder$GclAtom.sum((function (tag) {
        switch (tag) {
          case "Global" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* Global */Caml_chrome_debugger.variant("Global", 0, [Curry._1(Base$GclAtom.Loc.decode, json)]);
                          })]);
          case "Local" :
              var partial_arg = Base$GclAtom.Loc.decode;
              var partial_arg$1 = function (param) {
                return Json_decode.pair(partial_arg, Json_decode.$$int, param);
              };
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* Local */Caml_chrome_debugger.variant("Local", 1, [
                                                    param[0],
                                                    param[1]
                                                  ]);
                                        }), partial_arg$1, param);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

function toLoc(site, specifications) {
  if (site.tag) {
    var i = site[1];
    var loc = site[0];
    var specs = Rebase.$$Array.filter((function (spec) {
            return spec[/* id */0] === i;
          }), specifications);
    return Rebase.$$Option.mapOr((function (spec) {
                  return Base$GclAtom.Loc.translateBy(1, 0, 1, 0, Base$GclAtom.Loc.translate(loc, spec[/* loc */3]));
                }), loc, Rebase.$$Array.get(specs, 0));
  } else {
    return site[0];
  }
}

function toRange(site, specifications) {
  return Base$GclAtom.Loc.toRange(toLoc(site, specifications));
}

function toString(site) {
  if (site.tag) {
    return "at " + (Base$GclAtom.Loc.toString(site[0]) + (" in #" + String(site[1])));
  } else {
    return "at " + Base$GclAtom.Loc.toString(site[0]);
  }
}

exports.decode = decode;
exports.toLoc = toLoc;
exports.toRange = toRange;
exports.toString = toString;
/* decode Not a pure module */
