// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Base2$GclAtom = require("../GCL/Base2.bs.js");
var GCL$Guacamole = require("guacamole/lib/js/src/GCL.bs.js");
var Types$GclAtom = require("../Types.bs.js");
var Event$Guacamole = require("guacamole/lib/js/src/Util/Event.bs.js");
var Decoration$GclAtom = require("./Decoration.bs.js");
var Webapi__Dom__HtmlElement = require("bs-webapi/lib/js/src/Webapi/Webapi__Dom/Webapi__Dom__HtmlElement.js");

function make(param) {
  var containers = Belt_Array.keep(Belt_Array.concatMany(Belt_Array.map(Belt_Array.map(atom.workspace.getBottomPanels(), (function (prim) {
                      return atom.views.getView(prim);
                    })), (function (xs) {
                  return Belt_Array.keepMap(Array.prototype.slice.call(xs.childNodes), Webapi__Dom__HtmlElement.ofNode);
                }))), (function (elem) {
          return elem.className === "gcl-panel-container";
        }));
  var match = Belt_Array.get(containers, 0);
  if (match !== undefined) {
    return Caml_option.valFromOption(match);
  } else {
    var panelContainer = document.createElement("article");
    panelContainer.classList.add("gcl-panel-container");
    atom.workspace.addBottomPanel({
          item: panelContainer,
          priority: 0,
          visible: true
        });
    return panelContainer;
  }
}

function add(container, element) {
  container.appendChild(element);
  return /* () */0;
}

var PanelContainer = {
  make: make,
  add: add
};

function make$1(editor) {
  var onRequest = Event$Guacamole.make(/* () */0);
  var onResponse = Event$Guacamole.make(/* () */0);
  var container = make(/* () */0);
  atom.views.getView(editor).classList.add("gcl");
  var element = document.createElement("article");
  element.setAttribute("tabIndex", "-1");
  element.classList.add("gcl-panel");
  element.classList.add("native-key-bindings");
  container.appendChild(element);
  var linkDict = { };
  var delete_ = (function (id) {delete linkDict[id]});
  Curry._1(onResponse.on, (function (param) {
          if (param.tag) {
            var match = param[0];
            switch (match.tag | 0) {
              case /* MouseOver */0 :
                  var loc = match[0];
                  var key = GCL$Guacamole.Loc.toString(loc);
                  linkDict[key] = Decoration$GclAtom.markLink(loc, editor);
                  return /* () */0;
              case /* MouseOut */1 :
                  var key$1 = GCL$Guacamole.Loc.toString(match[0]);
                  Belt_Option.forEach(Js_dict.get(linkDict, key$1), (function (prim) {
                          prim.destroy();
                          return /* () */0;
                        }));
                  return delete_(key$1);
              case /* MouseClick */2 :
                  var range = Base2$GclAtom.Loc.toRange(match[0]);
                  editor.setSelectedScreenRange(range);
                  return /* () */0;
              
            }
          } else {
            return /* () */0;
          }
        }));
  return Types$GclAtom.View.make(editor, element, onRequest, onResponse);
}

exports.PanelContainer = PanelContainer;
exports.make = make$1;
/* Base2-GclAtom Not a pure module */
