// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var ReactDom = require("react-dom");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Base$GclAtom = require("../GCL/Base.bs.js");
var Panel$GclAtom = require("../View/Panel.bs.js");
var Types$GclAtom = require("../Types.bs.js");
var Decoration$GclAtom = require("./Decoration.bs.js");
var Webapi__Dom__HtmlElement = require("bs-webapi/lib/js/src/Webapi/Webapi__Dom/Webapi__Dom__HtmlElement.js");

function make(param) {
  var containers = Belt_Array.keep(Belt_Array.concatMany(Belt_Array.map(Belt_Array.map(atom.workspace.getBottomPanels(), (function (prim) {
                      return atom.views.getView(prim);
                    })), (function (xs) {
                  return Belt_Array.keepMap(Array.prototype.slice.call(xs.childNodes), Webapi__Dom__HtmlElement.ofNode);
                }))), (function (elem) {
          return elem.className === "gcl-panel-container";
        }));
  var match = Belt_Array.get(containers, 0);
  if (match !== undefined) {
    return Caml_option.valFromOption(match);
  } else {
    var panelContainer = document.createElement("article");
    panelContainer.classList.add("gcl-panel-container");
    atom.workspace.addBottomPanel({
          item: panelContainer,
          priority: 0,
          visible: true
        });
    return panelContainer;
  }
}

var PanelContainer = {
  make: make
};

function make$1(editor) {
  var container = make(/* () */0);
  atom.views.getView(editor).classList.add("gcl");
  var element = document.createElement("article");
  element.setAttribute("tabIndex", "-1");
  element.classList.add("gcl-panel");
  element.classList.add("native-key-bindings");
  var id = "gcl:" + String(editor.id);
  element.id = id;
  container.appendChild(element);
  var channels = Curry._1(Types$GclAtom.View.Channels.make, /* () */0);
  var events = Curry._1(Types$GclAtom.View.Events.make, /* () */0);
  var component = React.createElement(Panel$GclAtom.make, {
        channels: channels,
        events: events
      });
  ReactDom.render(component, element);
  var linkDict = { };
  var delete_ = (function (id) {delete linkDict[id]});
  Curry._1(channels.link.on, (function (param) {
          switch (param.tag | 0) {
            case /* MouseOver */0 :
                var loc = param[0];
                var key = Base$GclAtom.Loc.toString(loc);
                linkDict[key] = Decoration$GclAtom.markLink(loc, editor);
                return /* () */0;
            case /* MouseOut */1 :
                var key$1 = Base$GclAtom.Loc.toString(param[0]);
                Belt_Option.forEach(Js_dict.get(linkDict, key$1), (function (prim) {
                        prim.destroy();
                        return /* () */0;
                      }));
                return delete_(key$1);
            case /* MouseClick */2 :
                var range = Base$GclAtom.Loc.toRange(param[0]);
                editor.setSelectedScreenRange(range);
                return /* () */0;
            
          }
        }));
  return Curry._3(Types$GclAtom.View.Interface.make, editor, channels, events);
}

function destroy(editor) {
  var id = "gcl:" + String(editor.id);
  Belt_Option.forEach(Caml_option.nullable_to_opt(document.getElementById(id)), (function (element) {
          ReactDom.unmountComponentAtNode(element);
          element.remove();
          return /* () */0;
        }));
  atom.views.getView(editor).classList.remove("gcl");
  return /* () */0;
}

function make2(editor) {
  var view = make$1(editor);
  Curry._1(view.setActivation, true);
  return view;
}

function destroy2(view) {
  return destroy(view.editor);
}

exports.PanelContainer = PanelContainer;
exports.make = make$1;
exports.destroy = destroy;
exports.make2 = make2;
exports.destroy2 = destroy2;
/* react Not a pure module */
