// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Command = 0;

var $$Error = 0;

var $$Response = 0;

exports.Command = Command;
exports.$$Error = $$Error;
exports.$$Response = $$Response;
/* No side effect */
