// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Command = /* alias */0;

var $$Error = /* alias */0;

var $$Response = /* alias */0;

exports.Command = Command;
exports.$$Error = $$Error;
exports.$$Response = $$Response;
/* No side effect */
