// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var commandNames = /* array */[
  "toggle",
  "save",
  "refine"
];

function parse(param) {
  switch (param) {
    case "refine" :
        return /* Refine */2;
    case "save" :
        return /* Save */1;
    case "toggle" :
        return /* Toggle */0;
    default:
      return /* Save */1;
  }
}

var Command = {
  commandNames: commandNames,
  parse: parse
};

exports.Command = Command;
/* No side effect */
