// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var commandNames = /* array */[
  "toggle",
  "save"
];

function parse(param) {
  switch (param) {
    case "save" :
        return /* Save */1;
    case "toggle" :
        return /* Toggle */0;
    default:
      return /* Save */1;
  }
}

exports.commandNames = commandNames;
exports.parse = parse;
/* No side effect */
