// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var commandNames = /* array */[
  "activate",
  "deactivate",
  "save"
];

function parse(param) {
  switch (param) {
    case "activate" :
        return /* Activate */0;
    case "deactivate" :
        return /* Deactivate */1;
    case "save" :
        return /* Save */2;
    default:
      return /* Save */2;
  }
}

exports.commandNames = commandNames;
exports.parse = parse;
/* No side effect */
