// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Connection$Guacamole = require("guacamole/lib/js/src/Connection.bs.js");

function setGCLPath(value) {
  atom.config.set("gcl-atom.path", value);
  return $$Promise.resolved(/* () */0);
}

function getGCLPath(param) {
  return atom.config.get("gcl-atom.path");
}

var AtomImpl = {
  getGCLPath: getGCLPath,
  setGCLPath: setGCLPath
};

var include = Connection$Guacamole.Impl(AtomImpl);

var Process = include.Process;

var $$Error = include.$$Error;

var isConnected = include.isConnected;

var disconnect = include.disconnect;

var wire = include.wire;

var getGCLPath$1 = include.getGCLPath;

var validateGCLPath = include.validateGCLPath;

var make = include.make;

var send = include.send;

exports.AtomImpl = AtomImpl;
exports.Process = Process;
exports.$$Error = $$Error;
exports.isConnected = isConnected;
exports.disconnect = disconnect;
exports.wire = wire;
exports.getGCLPath = getGCLPath$1;
exports.validateGCLPath = validateGCLPath;
exports.make = make;
exports.send = send;
/* include Not a pure module */
