// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var AtomImpl$GclAtom = require("./Editor/AtomImpl.bs.js");
var Connection$Guacamole = require("guacamole/lib/js/src/Connection.bs.js");

var include = Connection$Guacamole.Impl({
      make: AtomImpl$GclAtom.make,
      getExtensionPath: AtomImpl$GclAtom.getExtensionPath,
      editorFileName: AtomImpl$GclAtom.editorFileName,
      onDidChangeFileName: AtomImpl$GclAtom.onDidChangeFileName,
      onDidChangeActivation: AtomImpl$GclAtom.onDidChangeActivation,
      onDidCloseEditor: AtomImpl$GclAtom.onDidCloseEditor,
      addToSubscriptions: AtomImpl$GclAtom.addToSubscriptions,
      registerCommand: AtomImpl$GclAtom.registerCommand,
      getGCLPath: AtomImpl$GclAtom.getGCLPath,
      setGCLPath: AtomImpl$GclAtom.setGCLPath
    });

var Process = include.Process;

var $$Error = include.$$Error;

var isConnected = include.isConnected;

var disconnect = include.disconnect;

var wire = include.wire;

var getGCLPath = include.getGCLPath;

var validateGCLPath = include.validateGCLPath;

var make = include.make;

var send = include.send;

exports.Process = Process;
exports.$$Error = $$Error;
exports.isConnected = isConnected;
exports.disconnect = disconnect;
exports.wire = wire;
exports.getGCLPath = getGCLPath;
exports.validateGCLPath = validateGCLPath;
exports.make = make;
exports.send = send;
/* include Not a pure module */
