// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Atom = require("atom");
var Curry = require("bs-platform/lib/js/curry.js");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");

function handle(instance, param) {
  if (param) {
    var decorate = function (param) {
      var pos = param[0];
      Curry._1(instance[/* view */1][/* setHeader */1], "Parse error");
      Curry._1(instance[/* view */1][/* setBody */2], param[1]);
      var range = new Atom.Range(pos, pos);
      var marker = instance[/* editor */0].markBufferRange(range);
      var option = {
        type: "line",
        class: "marker-error"
      };
      return instance[/* editor */0].decorateMarker(marker, option);
    };
    var decorations = Rebase.$$Array.map(decorate, param[0]);
    instance[/* decorations */3] = Rebase.$$Array.concat(instance[/* decorations */3], decorations);
    return /* () */0;
  } else {
    Curry._1(instance[/* view */1][/* setHeader */1], "All good");
    Curry._1(instance[/* view */1][/* setBody */2], "");
    return /* () */0;
  }
}

exports.handle = handle;
/* atom Not a pure module */
