// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Atom = require("atom");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");

function handle(instance, param) {
  if (param) {
    var decorate = function (param) {
      var pos = param[0];
      var pos$prime = new Atom.Point(-1, 0).translate(pos);
      var range = new Atom.Range(pos$prime, pos$prime);
      console.log(pos);
      console.log(range);
      var marker = instance[/* editor */0].markBufferRange(range);
      var option = {
        type: "line",
        class: "marker-error"
      };
      return instance[/* editor */0].decorateMarker(marker, option);
    };
    var decorations = Rebase.$$Array.map(decorate, param[0]);
    instance[/* decorations */2] = Rebase.$$Array.concat(instance[/* decorations */2], decorations);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

exports.handle = handle;
/* atom Not a pure module */
