// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Atom = require("atom");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Main$Guacamole = require("guacamole/lib/js/src/Main.bs.js");
var State2$GclAtom = require("./State2.bs.js");
var AtomImpl$GclAtom = require("./Editor/AtomImpl.bs.js");

var partial_arg = {
  make: AtomImpl$GclAtom.make,
  getExtensionPath: AtomImpl$GclAtom.getExtensionPath,
  editorFileName: AtomImpl$GclAtom.editorFileName,
  onDidChangeFileName: AtomImpl$GclAtom.onDidChangeFileName,
  onDidChangeActivation: AtomImpl$GclAtom.onDidChangeActivation,
  onDidCloseEditor: AtomImpl$GclAtom.onDidCloseEditor,
  addToSubscriptions: AtomImpl$GclAtom.addToSubscriptions,
  registerCommand: AtomImpl$GclAtom.registerCommand,
  getGCLPath: AtomImpl$GclAtom.getGCLPath,
  setGCLPath: AtomImpl$GclAtom.setGCLPath
};

var partial_arg$1 = Main$Guacamole.Impl;

var Main = (function (param) {
      return partial_arg$1(partial_arg, param);
    })(State2$GclAtom.Impl);

var activated = {
  contents: undefined
};

function activate(param) {
  if (Belt_Option.isNone(activated.contents)) {
    var subscriptions = new Atom.CompositeDisposable();
    activated.contents = Caml_option.some(subscriptions);
    Curry._1(Main.activate, subscriptions);
  }
  return Promise.resolve(/* () */0);
}

function deactivate(param) {
  return Belt_Option.forEach(activated.contents, (function (subscriptions) {
                subscriptions.dispose();
                activated.contents = undefined;
                return Curry._1(Main.deactivate, /* () */0);
              }));
}

var config = {
  path: {
    title: "GCL path",
    description: "Path to the executable of GCL, automatically inferred when possible. Overwrite to override.",
    type: "string",
    default: "",
    order: 1
  }
};

exports.Main = Main;
exports.activated = activated;
exports.activate = activate;
exports.deactivate = deactivate;
exports.config = config;
/* Main Not a pure module */
