// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Atom = require("atom");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Async$GclAtom = require("./Util/Async.bs.js");
var Command$GclAtom = require("./Command.bs.js");
var Instance$GclAtom = require("./Instance.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var activated = /* record */Caml_chrome_debugger.record(["contents"], [false]);

var instances = { };

function textEditorID(textEditor) {
  return String(textEditor.id);
}

function get(textEditor) {
  return Js_dict.get(instances, String(textEditor.id));
}

function getThen(f, textEditor) {
  return Rebase.$$Option.forEach(f, Js_dict.get(instances, String(textEditor.id)));
}

function add(textEditor) {
  var match = Js_dict.get(instances, String(textEditor.id));
  if (match !== undefined) {
    return /* () */0;
  } else {
    instances[String(textEditor.id)] = Instance$GclAtom.make(textEditor);
    return /* () */0;
  }
}

function delete_ (id){{delete instances[id]}};

function remove(textEditor) {
  var id = String(textEditor.id);
  var match = Js_dict.get(instances, id);
  if (match !== undefined) {
    Instance$GclAtom.destroy(match);
    delete_(id);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

function destroyAll(param) {
  return Rebase.$$Array.forEach((function (param) {
                Instance$GclAtom.destroy(param[1]);
                delete_(param[0]);
                return /* () */0;
              }), Js_dict.entries(instances));
}

function contains(textEditor) {
  return Js_dict.get(instances, String(textEditor.id)) !== undefined;
}

function size(param) {
  return Rebase.$$Array.length(Object.keys(instances));
}

var Instances = {
  textEditorID: textEditorID,
  get: get,
  getThen: getThen,
  add: add,
  delete_: delete_,
  remove: remove,
  destroyAll: destroyAll,
  contains: contains,
  size: size
};

function isGCLFile(textEditor) {
  var filepath = Rebase.$$Option.getOr("untitled", textEditor.getPath());
  return (/\.gcl$/i).test(filepath);
}

var subscriptions = new Atom.CompositeDisposable();

function onEditorActivationChange(param) {
  var previous = /* record */Caml_chrome_debugger.record(["contents"], [atom.workspace.getActiveTextEditor()]);
  subscriptions.add(atom.workspace.onDidChangeActiveTextEditor((function (next) {
              Rebase.$$Option.forEach((function (param) {
                      return getThen(Instance$GclAtom.hideView, param);
                    }), previous[0]);
              if (next !== undefined) {
                var nextEditor = Caml_option.valFromOption(next);
                getThen(Instance$GclAtom.showView, nextEditor);
                previous[0] = Caml_option.some(nextEditor);
                return /* () */0;
              } else {
                return /* () */0;
              }
            })));
  return /* () */0;
}

function eventTargetEditor($$event) {
  var targetSubElement = $$event.target;
  var targetedEditors = Rebase.$$Array.filter((function (x) {
          return atom.views.getView(x).contains(targetSubElement);
        }), atom.workspace.getTextEditors());
  return Rebase.$$Array.get(targetedEditors, 0);
}

function onTriggerCommand(param) {
  return Rebase.$$Array.forEach((function (command) {
                subscriptions.add(atom.commands.add("atom-text-editor", "gcl-atom:" + command, (function ($$event) {
                            return Rebase.$$Option.forEach((function (instance) {
                                          Async$GclAtom.thenOk((function (param) {
                                                    return Instance$GclAtom.runTasks(instance, param);
                                                  }))(Instance$GclAtom.dispatchRaw(Command$GclAtom.Raw.parse(command), instance));
                                          return /* () */0;
                                        }), Rebase.$$Option.flatMap(get, eventTargetEditor($$event)));
                          })));
                return /* () */0;
              }), Command$GclAtom.Raw.commandNames);
}

function onOpenEditor(param) {
  subscriptions.add(atom.workspace.observeTextEditors((function (textEditor) {
              var textEditorSubscriptions = new Atom.CompositeDisposable();
              if (isGCLFile(textEditor)) {
                add(textEditor);
              }
              textEditorSubscriptions.add(textEditor.onDidChangePath((function (param) {
                          if (!isGCLFile(textEditor) && contains(textEditor)) {
                            remove(textEditor);
                          }
                          if (isGCLFile(textEditor) && !contains(textEditor)) {
                            return add(textEditor);
                          } else {
                            return 0;
                          }
                        })));
              textEditorSubscriptions.add(textEditor.onDidDestroy((function (param) {
                          if (isGCLFile(textEditor) && contains(textEditor)) {
                            remove(textEditor);
                          }
                          textEditorSubscriptions.dispose();
                          return /* () */0;
                        })));
              return /* () */0;
            })));
  return /* () */0;
}

function setup(param) {
  onOpenEditor(/* () */0);
  onEditorActivationChange(/* () */0);
  return onTriggerCommand(/* () */0);
}

function activate(param) {
  if (!activated[0]) {
    activated[0] = true;
    setup(/* () */0);
  }
  return Promise.resolve(/* () */0);
}

function deactivate(param) {
  if (activated[0]) {
    activated[0] = false;
    destroyAll(/* () */0);
    subscriptions.dispose();
    return /* () */0;
  } else {
    return 0;
  }
}

exports.activated = activated;
exports.instances = instances;
exports.Instances = Instances;
exports.isGCLFile = isGCLFile;
exports.subscriptions = subscriptions;
exports.onEditorActivationChange = onEditorActivationChange;
exports.eventTargetEditor = eventTargetEditor;
exports.onTriggerCommand = onTriggerCommand;
exports.onOpenEditor = onOpenEditor;
exports.setup = setup;
exports.activate = activate;
exports.deactivate = deactivate;
/* subscriptions Not a pure module */
