// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Body$GclAtom = require("./View/Body.bs.js");
var Pred$GclAtom = require("./View/Pred.bs.js");
var Decoder$GclAtom = require("./Decoder.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var decode = Decoder$GclAtom.sum((function (tag) {
        switch (tag) {
          case "DigHole" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* DigHole */Caml_chrome_debugger.variant("DigHole", 3, [Decoder$GclAtom.range(json)]);
                          })]);
          case "ExcessBound" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* ExcessBound */Caml_chrome_debugger.variant("ExcessBound", 2, [Decoder$GclAtom.range(json)]);
                          })]);
          case "MissingAssertion" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* MissingAssertion */Caml_chrome_debugger.variant("MissingAssertion", 1, [Decoder$GclAtom.range(json)]);
                          })]);
          case "MissingBound" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* MissingBound */Caml_chrome_debugger.variant("MissingBound", 0, [Decoder$GclAtom.range(json)]);
                          })]);
          case "MissingPostcondition" :
              return /* TagOnly */Caml_chrome_debugger.variant("TagOnly", 1, [(function (param) {
                            return /* MissingPostcondition */0;
                          })]);
          case "Panic" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* Panic */Caml_chrome_debugger.variant("Panic", 4, [Json_decode.string(json)]);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

var Convert = {
  decode: decode
};

function decode$1(json) {
  return /* record */Caml_chrome_debugger.record([
            "location",
            "message"
          ], [
            Json_decode.field("synErrLocation", Decoder$GclAtom.range, json),
            Json_decode.field("synErrMessage", Json_decode.string, json)
          ]);
}

var Syntactic = {
  decode: decode$1
};

var decode$2 = Decoder$GclAtom.sum((function (tag) {
        switch (tag) {
          case "ConvertError" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* ConvertError */Caml_chrome_debugger.variant("ConvertError", 2, [Curry._1(decode, json)]);
                          })]);
          case "LexicalError" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* LexicalError */Caml_chrome_debugger.variant("LexicalError", 0, [Decoder$GclAtom.point(json)]);
                          })]);
          case "SyntacticError" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* SyntacticError */Caml_chrome_debugger.variant("SyntacticError", 1, [decode$1(json)]);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

var decode$3 = Decoder$GclAtom.sum((function (tag) {
        switch (tag) {
          case "Global" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (json) {
                            return /* Global */Caml_chrome_debugger.variant("Global", 0, [Decoder$GclAtom.range(json)]);
                          })]);
          case "Local" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* Local */Caml_chrome_debugger.variant("Local", 1, [
                                                    param[0],
                                                    param[1]
                                                  ]);
                                        }), (function (param) {
                                          return Json_decode.pair(Decoder$GclAtom.range, Json_decode.$$int, param);
                                        }), param);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

var Site = {
  decode: decode$3
};

var $$Error = {
  Convert: Convert,
  Syntactic: Syntactic,
  decode: decode$2,
  Site: Site
};

function decodeHardness(param) {
  return Json_decode.map((function (tag) {
                switch (tag) {
                  case "Hard" :
                      return /* Hard */0;
                  case "Soft" :
                      return /* Soft */1;
                  default:
                    throw [
                          Json_decode.DecodeError,
                          "Unknown constructor: " + tag
                        ];
                }
              }), Json_decode.string, param);
}

function decode$4(json) {
  return /* record */Caml_chrome_debugger.record([
            "id",
            "hardness",
            "pre",
            "post",
            "range"
          ], [
            Json_decode.field("specID", Json_decode.$$int, json),
            Json_decode.field("specHardness", decodeHardness, json),
            Json_decode.field("specPreCond", Pred$GclAtom.decode, json),
            Json_decode.field("specPostCond", Pred$GclAtom.decode, json),
            Json_decode.field("specLoc", Decoder$GclAtom.range, json)
          ]);
}

var Specification = {
  decodeHardness: decodeHardness,
  decode: decode$4
};

var decode$5 = Decoder$GclAtom.sum((function (tag) {
        switch (tag) {
          case "Error" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (pairs) {
                                          return /* Error */Caml_chrome_debugger.variant("Error", 0, [pairs]);
                                        }), (function (param) {
                                          return Json_decode.array((function (param) {
                                                        return Json_decode.pair(decode$3, decode$2, param);
                                                      }), param);
                                        }), param);
                          })]);
          case "OK" :
              var partial_arg = Body$GclAtom.ProofObligation.decode;
              var partial_arg$1 = function (param) {
                return Json_decode.array(partial_arg, param);
              };
              var partial_arg$2 = function (param) {
                return Json_decode.pair(partial_arg$1, (function (param) {
                              return Json_decode.array(decode$4, param);
                            }), param);
              };
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (param) {
                                          return /* OK */Caml_chrome_debugger.variant("OK", 1, [
                                                    param[0],
                                                    param[1]
                                                  ]);
                                        }), partial_arg$2, param);
                          })]);
          case "Resolve" :
              return /* Contents */Caml_chrome_debugger.variant("Contents", 0, [(function (param) {
                            return Json_decode.map((function (i) {
                                          return /* Resolve */Caml_chrome_debugger.variant("Resolve", 2, [i]);
                                        }), Json_decode.$$int, param);
                          })]);
          default:
            throw [
                  Json_decode.DecodeError,
                  "Unknown constructor: " + tag
                ];
        }
      }));

exports.$$Error = $$Error;
exports.Specification = Specification;
exports.decode = decode$5;
/* decode Not a pure module */
