// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Ok$GclAtom = require("./Util/Ok.bs.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var View$GclAtom = require("./Editor/View.bs.js");
var Types$GclAtom = require("./Types.bs.js");
var Response$GclAtom = require("./GCL/Response.bs.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var Connection$GclAtom = require("./Connection.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function toString(param) {
  if (param.tag) {
    return /* tuple */[
            "JSON Decode Error",
            param[0] + ("\nJSON from GCL: \n" + JSON.stringify(param[1]))
          ];
  } else {
    return Curry._1(Connection$GclAtom.$$Error.toString, param[0]);
  }
}

var $$Error = {
  toString: toString
};

function make(editor) {
  return {
          editor: editor,
          view: View$GclAtom.make(editor),
          toggle: false,
          connection: undefined,
          decorations: [],
          specifications: [],
          history: undefined
        };
}

function showView(state) {
  Curry._1(state.view.setActivation, true);
  return /* () */0;
}

function hideView(state) {
  Curry._1(state.view.setActivation, true);
  return /* () */0;
}

function displayError(header, body, state) {
  Curry._1(state.view.setHeader, /* Error */Caml_chrome_debugger.variant("Error", 1, [header]));
  Curry._1(state.view.setBody, /* Plain */Caml_chrome_debugger.variant("Plain", 1, [body]));
  return /* () */0;
}

function establishConnection(state) {
  var match = state.connection;
  if (match !== undefined) {
    return $$Promise.resolved(/* Ok */Caml_chrome_debugger.variant("Ok", 0, [match]));
  } else {
    return $$Promise.tapOk($$Promise.mapError(Curry._1(Connection$GclAtom.make, /* () */0), (function (e) {
                      return /* Connection */Caml_chrome_debugger.variant("Connection", 0, [e]);
                    })), (function (conn) {
                  state.connection = conn;
                  return /* () */0;
                }));
  }
}

function sendRequest(request, state) {
  var value = Types$GclAtom.$$Request.encode(request);
  console.log("<<<", value);
  return Ok$GclAtom.let_(establishConnection(state), (function (conn) {
                return Ok$GclAtom.let_($$Promise.mapError(Curry._2(Connection$GclAtom.send, value, conn), (function (e) {
                                  return /* Connection */Caml_chrome_debugger.variant("Connection", 0, [e]);
                                })), (function (result) {
                              console.log(">>>", result);
                              var value;
                              try {
                                value = Response$GclAtom.decode(result);
                              }
                              catch (raw_exn){
                                var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                                if (exn[0] === Json_decode.DecodeError) {
                                  return $$Promise.resolved(/* Error */Caml_chrome_debugger.variant("Error", 1, [/* Decode */Caml_chrome_debugger.variant("Decode", 1, [
                                                    exn[1],
                                                    result
                                                  ])]));
                                } else {
                                  throw exn;
                                }
                              }
                              return $$Promise.resolved(/* Ok */Caml_chrome_debugger.variant("Ok", 0, [value]));
                            }));
              }));
}

function destroy(state) {
  state.toggle = false;
  Curry._1(state.view.setActivation, false);
  View$GclAtom.destroy(state.editor);
  Belt_Array.forEach(state.decorations, (function (prim) {
          prim.destroy();
          return /* () */0;
        }));
  state.specifications = [];
  state.history = undefined;
  return Belt_Option.forEach(state.connection, (function (conn) {
                Curry._1(Connection$GclAtom.disconnect, conn);
                state.connection = undefined;
                return /* () */0;
              }));
}

exports.$$Error = $$Error;
exports.make = make;
exports.showView = showView;
exports.hideView = hideView;
exports.displayError = displayError;
exports.establishConnection = establishConnection;
exports.sendRequest = sendRequest;
exports.destroy = destroy;
/* Promise Not a pure module */
