// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Ok$GclAtom = require("./Util/Ok.bs.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var View$GclAtom = require("./Editor/View.bs.js");
var Types$GclAtom = require("./Types.bs.js");
var AtomImpl$GclAtom = require("./Editor/AtomImpl.bs.js");
var Response$GclAtom = require("./GCL/Response.bs.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");
var Connection$Guacamole = require("guacamole/lib/js/src/Connection.bs.js");

function make(editor) {
  var view = View$GclAtom.make(editor);
  var state = {
    editor: editor,
    view: view,
    loaded: false,
    mode: /* WP1 */0,
    connection: undefined,
    decorations: [],
    specifications: [],
    history: undefined
  };
  Curry._1(view.onSetMode.on, (function (mode) {
          state.mode = mode;
          return /* () */0;
        }));
  return state;
}

function showView(state) {
  if (state.loaded) {
    Curry._1(state.view.setActivation, true);
    return /* () */0;
  } else {
    return 0;
  }
}

function hideView(state) {
  if (state.loaded) {
    Curry._1(state.view.setActivation, false);
    return /* () */0;
  } else {
    return 0;
  }
}

function displayError(header, body, state) {
  Curry._1(state.view.setHeader, /* Error */Caml_chrome_debugger.variant("Error", 1, [header]));
  Curry._1(state.view.setBody, /* Plain */Caml_chrome_debugger.variant("Plain", 1, [body]));
  return /* () */0;
}

function establishConnection(state) {
  var match = state.connection;
  if (match !== undefined) {
    return $$Promise.resolved(/* Ok */Caml_chrome_debugger.variant("Ok", 0, [match]));
  } else {
    return $$Promise.tapOk($$Promise.mapError(Connection$Guacamole.make(AtomImpl$GclAtom.Impl.Config.getGCLPath, AtomImpl$GclAtom.Impl.Config.setGCLPath), (function (e) {
                      return /* Connection */Caml_chrome_debugger.variant("Connection", 0, [e]);
                    })), (function (conn) {
                  state.connection = conn;
                  return /* () */0;
                }));
  }
}

function sendRequest(request, state) {
  var value = Types$GclAtom.$$Request.encode(request);
  console.log("<<<", value);
  return Ok$GclAtom.let_(establishConnection(state), (function (conn) {
                return Ok$GclAtom.let_($$Promise.mapError(Connection$Guacamole.send(value, conn), (function (e) {
                                  return /* Connection */Caml_chrome_debugger.variant("Connection", 0, [e]);
                                })), (function (result) {
                              console.log(">>>", result);
                              var value;
                              try {
                                value = Response$GclAtom.decode(result);
                              }
                              catch (raw_exn){
                                var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                                if (exn[0] === Json_decode.DecodeError) {
                                  return $$Promise.resolved(/* Error */Caml_chrome_debugger.variant("Error", 1, [/* Decode */Caml_chrome_debugger.variant("Decode", 1, [
                                                    exn[1],
                                                    result
                                                  ])]));
                                } else {
                                  throw exn;
                                }
                              }
                              return $$Promise.resolved(/* Ok */Caml_chrome_debugger.variant("Ok", 0, [value]));
                            }));
              }));
}

function cleanup(state) {
  hideView(state);
  state.loaded = false;
  Belt_Array.forEach(state.decorations, (function (prim) {
          prim.destroy();
          return /* () */0;
        }));
  state.specifications = [];
  state.history = undefined;
  return Belt_Option.forEach(state.connection, (function (conn) {
                Connection$Guacamole.disconnect(conn);
                state.connection = undefined;
                return /* () */0;
              }));
}

function destroy(state) {
  cleanup(state);
  return View$GclAtom.destroy(state.editor);
}

var $$Error = /* alias */0;

exports.$$Error = $$Error;
exports.make = make;
exports.showView = showView;
exports.hideView = hideView;
exports.displayError = displayError;
exports.establishConnection = establishConnection;
exports.sendRequest = sendRequest;
exports.cleanup = cleanup;
exports.destroy = destroy;
/* Promise Not a pure module */
