// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Channel$GclAtom = require("./Util/Channel.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function make(param) {
  return /* record */Caml_chrome_debugger.record([
            "updateConnection",
            "setActivation",
            "setHeader",
            "setBody"
          ], [
            Channel$GclAtom.make(/* () */0),
            Channel$GclAtom.make(/* () */0),
            Channel$GclAtom.make(/* () */0),
            Channel$GclAtom.make(/* () */0)
          ]);
}

var Channels = {
  make: make
};

function make$1(channels) {
  var partial_arg = channels[/* setActivation */1];
  var partial_arg$1 = channels[/* setHeader */2];
  var partial_arg$2 = channels[/* setBody */3];
  return /* record */Caml_chrome_debugger.record([
            "setActivation",
            "setHeader",
            "setBody"
          ], [
            (function (param) {
                return Channel$GclAtom.sendTo(partial_arg, param);
              }),
            (function (param) {
                return Channel$GclAtom.sendTo(partial_arg$1, param);
              }),
            (function (param) {
                return Channel$GclAtom.sendTo(partial_arg$2, param);
              })
          ]);
}

var Interface = {
  make: make$1
};

var View = {
  Channels: Channels,
  Interface: Interface
};

exports.View = View;
/* No side effect */
