// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Webapi = require("bs-webapi/lib/js/src/Webapi.js");
var ReactDom = require("react-dom");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Webapi__Dom = require("bs-webapi/lib/js/src/Webapi/Webapi__Dom.js");
var Hook$GclAtom = require("./View/Hook.bs.js");
var Async$GclAtom = require("./Util/Async.bs.js");
var Channel$GclAtom = require("./Util/Channel.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");
var Webapi__Dom__HtmlElement = require("bs-webapi/lib/js/src/Webapi/Webapi__Dom/Webapi__Dom__HtmlElement.js");

function make(param) {
  var containers = Rebase.$$Array.filter((function (elem) {
          return elem.className === "gcl-panel-container";
        }), Rebase.$$Array.flatMap((function (xs) {
              return Rebase.$$Array.filterMap(Webapi__Dom__HtmlElement.ofNode, Array.prototype.slice.call(xs.childNodes));
            }), Rebase.$$Array.map((function (prim) {
                  return atom.views.getView(prim);
                }), atom.workspace.getBottomPanels())));
  var match = Rebase.$$Array.get(containers, 0);
  if (match !== undefined) {
    return Caml_option.valFromOption(match);
  } else {
    var panelContainer = document.createElement("article");
    panelContainer.classList.add("gcl-panel-container");
    atom.workspace.addBottomPanel({
          item: panelContainer,
          priority: 0,
          visible: true
        });
    return panelContainer;
  }
}

var PanelContainer = {
  make: make
};

function make$1(param) {
  return /* record */Caml_chrome_debugger.record([
            "updateConnection",
            "setActivation",
            "setHeader",
            "setBody"
          ], [
            Channel$GclAtom.make(/* () */0),
            Channel$GclAtom.make(/* () */0),
            Channel$GclAtom.make(/* () */0),
            Channel$GclAtom.make(/* () */0)
          ]);
}

var Channels = {
  make: make$1
};

function View(Props) {
  var channels = Props.channels;
  var match = Hook$GclAtom.useState("");
  var setHeader = match[1];
  var match$1 = Hook$GclAtom.useState("");
  var setBody = match$1[1];
  var match$2 = Hook$GclAtom.useState(false);
  var setActivation = match$2[1];
  Hook$GclAtom.useChannel((function (x) {
          return Async$GclAtom.resolve(Curry._1(setHeader, x));
        }), channels[/* setHeader */2]);
  Hook$GclAtom.useChannel((function (x) {
          return Async$GclAtom.resolve(Curry._1(setBody, x));
        }), channels[/* setBody */3]);
  Hook$GclAtom.useChannel((function (x) {
          return Async$GclAtom.resolve(Curry._1(setActivation, x));
        }), channels[/* setActivation */1]);
  return React.createElement("section", {
              className: match$2[0] ? "" : "hidden"
            }, React.createElement("h2", undefined, match[0]), React.createElement("div", undefined, match$1[0]));
}

function make$2(editor, channels) {
  return /* record */Caml_chrome_debugger.record([
            "destroy",
            "setActivation",
            "setHeader",
            "setBody"
          ], [
            (function (param) {
                var id = "gcl:" + String(editor.id);
                return Rebase.$$Option.forEach((function (element) {
                              ReactDom.unmountComponentAtNode(element);
                              element.remove();
                              return /* () */0;
                            }), Caml_option.nullable_to_opt(document.getElementById(id)));
              }),
            (function (s) {
                return Channel$GclAtom.send(s, channels[/* setActivation */1]);
              }),
            (function (s) {
                return Channel$GclAtom.send(s, channels[/* setHeader */2]);
              }),
            (function (s) {
                return Channel$GclAtom.send(s, channels[/* setBody */3]);
              })
          ]);
}

var Interface = {
  make: make$2
};

function create(editor) {
  var container = make(/* () */0);
  var element = document.createElement("article");
  element.classList.add("gcl-panel");
  var id = "gcl:" + String(editor.id);
  element.id = id;
  container.appendChild(element);
  var channels = make$1(/* () */0);
  var component = React.createElement(View, {
        channels: channels
      });
  ReactDom.render(component, element);
  return make$2(editor, channels);
}

var make$3 = View;

exports.PanelContainer = PanelContainer;
exports.Channels = Channels;
exports.make = make$3;
exports.Interface = Interface;
exports.create = create;
/* react Not a pure module */
